### PR TITLE
ignore .idea + update build & dependencies

### PR DESCRIPTION
**Pull request by francisdb**
see also #1

### CODE REVIEW

**Comment by kimar** [comment]
Thx and 👍 Looking forward to see this thing evolve, at last.

**Comment by francisdb** [comment]
Well we would like to test the service and therefore we need an android client :-)
Would also be nice if we could set up the geofences through the api. That would make the app like a simple agent that sets up fences and sends events.

**Comment by kimar** [comment]
You mean like adding Geofences using the Web App?
This is already possible using the interface and opening up an oAuth2 endpoint for this shouldn't be a big deal im-/exporting is already possible on iOS. Although this has to be done manually right now. Sounds to me like you'd rather like to get the Geofences imported into the App automatically?

**Comment by francisdb** [comment]
Yes, app without ui, geofences stored/configured on serverside.

**Pull request merged**
